import AnimatedText from "@/components/AnimatedText";
import Layout from "@/components/Layout";
import Head from "next/head";
import React from "react";
import profilepic from "../../public/images/profile/profile.png";
import Image from "next/image";

const about = () => {
  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="w-full ">
        <Layout className="pt-16">
          <AnimatedText
            text="Passion Fuels Purpose! "
            className="flex flex-wrap justify-center items-center text-8xl mb-16"
          />
          <div className="grid w-full grid-cols-8 gap-16 m-9">
            <div className="col-span-3 flex flex-col justify-start ">
              <h2 className="text-lg font-bold text-dark/75 uppercase">
                Biography
              </h2>
              <p className="text-justify mt-2 font-medium">
                Hi, I am Chathurka, a Frontend developer and UI/UX designer with
                a passion for creating beautiful, functional, and user-centered
                digital experiences. With more than 2 years of experience in the
                field. I am always looking for new and innovative ways to bring
                my clients visions to life.
              </p>
              <p className="text-justify my-3 font-medium">
                I believe that design is about more than just making things look
                pretty. its about solving problems and creating intuitive,
                enjoyable experiences for users
              </p>

              <p className="text-justif font-medium mt-2">
                Whether Im working on a website, mobile app, or other digital
                product, I bring my commitment to design excellence and
                user-centered thinking to every project I work on. I look
                forward to the opportunity to bring my skills and passion to
                your next project.
              </p>
            </div>
            <div className="col-span-3 flex flex-col justify-center items-center ">
              <div className="flex p-5 w-[60%] border w-100 border-solid rounded-2xl border-dark justify-center items-center">
                <Image alt="profile" src={profilepic} className="rounded-2xl " />
              </div>
            </div>
            {/* <div className="col-span-1 flex flex-col justify-start ">
              <h2 className="text-lg font-bold text-dark uppercase">
                Biography
              </h2>
            </div> */}
          </div>
        </Layout>
      </main>
    </>
  );
};

export default about;
