import AnimatedText from "@/components/AnimatedText";
import Layout from "@/components/Layout";
import Head from "next/head";
import React from "react";
import project1 from "../../public/images/projects/project1.png";
import project2 from "../../public/images/projects/project2.png";
import project3 from "../../public/images/projects/project3.png";
import project4 from "../../public/images/projects/project4.png";
import project5 from "../../public/images/projects/project5.png";
import Image from "next/image";
import Link from "next/link";
import { GithubIcon } from "@/components/Icons";

const LatestProject = ({ title, summary, img, link, technology, viewPage }) => {
  return (
    <>
      <div className="col-span-6 overflow-hidden">
        <Image src={img} alt={title} className="w-full h-auto hover:transform hover:scale-105 hover:duration-500 " />
      </div>
      <div className="col-span-6">
        <h2 className="text-3xl font-bold text-dark ">{title}</h2>
        <p className="my-5 text-justify">{summary}</p>
        <p className="my-5">
          Developed using <strong>{technology}</strong>
        </p>

        <div className="flex justify-start items-center mt-10">
          <Link href={link}  target="_blank" className="w-10 h-10 mr-5">
            <GithubIcon  />
          </Link>
          <Link
            href={viewPage}
            target="_blank"
            className="p-3 bg-dark font-bold rounded-2xl text-light"
          >
            View Project
          </Link>
        </div>
      </div>
    </>
  );
};

const FeaturedProjects = ({
  title,
  summary,
  img,
  link,
  technology,
  viewPage,
}) => {
  return (
    <>
      <div className="col-span-6 overflow-hidden">
        <Image src={img} alt={title} className="w-full h-auto mb-5 hover:transform hover:scale-105 hover:duration-500" />
      </div>
      <div className="col-span-6">
        <h2 className="text-3xl font-bold text-dark ">{title}</h2>
        <p className="my-5 text-justify">{summary}</p>
        <p className="my-5">
          Developed using <strong>{technology}</strong>
        </p>

        <div className="flex justify-start items-center mt-10">
          <Link href={viewPage}  target="_blank" className="w-10 h-10 mr-5 ">
            <GithubIcon  />
          </Link>
          <Link
            href={link}
            target="_blank"
            className="p-3 bg-dark font-bold rounded-2xl text-light"
          >
            View Project
          </Link>
        </div>
      </div>
    </>
  );
};

const projects = () => {
  return (
    <>
      <Head>
        <title>Project Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="w-full ">
        <Layout className="pt-16">
          <AnimatedText
            text="Imagination Trumps Knowledge! "
            className="flex flex-wrap justify-center items-center text-8xl mb-16"
          />

          <div className=" items-center grid w-full grid-cols-12 gap-16 border-2 border-solid p-9 rounded-lg border-dark">
            <LatestProject
              img={project2}
              title="Land Management Sysytem"
              summary="The Land Payment Management System presents an innovative solution to revolutionize the land buying experience. By simplifying payment processes and providing real-time insights, our system enhances efficiency and transparency for both customers and land managers. With streamlined communication and secure payment gateways, the platform fosters stronger relationships and ensures a positive experience throughout the land buying journey. Overall, our project aims to empower stakeholders with an efficient and engaging payment management solution, driving the real estate industry towards enhanced customer satisfaction and operational excellence."
              technology="React JS, Next Js, TypeScript, MUI, Prisma"
              link=""
              viewPage="https://sevenseaslands.web.lk/login"
            />
          </div>

          <div className=" mt-10 mb-10 items-center grid w-full grid-cols-12 gap-16 ">
            <div className="col-span-6 min-h-[850px] flex flex-col border-2 border-solid p-9 rounded-lg border-dark">
              <FeaturedProjects
                img={project1}
                title="Home Construction Sysytem"
                summary="The House Plan and Details Prediction Component developed in
                          this research will significantly contribute to the advancement
                          of the Home Construction industry. Empowering customers with
                          accurate square footage predictions will not only streamline the
                          decision-making process but also enhance overall efficiency and
                          resource utilization. By harnessing the potential of Machine
                          Learning, we aim to revolutionize the construction sector,
                          providing a valuable tool for both construction companies and
                          potential homeowners."
                technology="React JS, Laravel (PHP), Flask(Python), Machine Learning (ML),
                            Bootstrap and CSS"
                link="https://github.com/chathurkavishmantha/Efficient-Cost-Effective-and-Time-Saving-Home-Construction-System"
                viewPage="https://github.com/chathurkavishmantha/Efficient-Cost-Effective-and-Time-Saving-Home-Construction-System"
              />
            </div>
            <div className="col-span-6 min-h-[850px] flex flex-col border-2 border-solid p-9 rounded-lg border-dark">
              <FeaturedProjects
                img={project3}
                title="Fitness Web Application"
                summary="Unrivaled Gym. Unparalleled Training Fitness Classes. World Class Studios to get the Body Shapes That you Dream of.. Get Your Dream Body Now.."
                technology="React JS, TypeScript, TailwindCss"
                link="https://github.com/chathurkavishmantha/Efficient-Cost-Effective-and-Time-Saving-Home-Construction-System"
                viewPage="https://github.com/chathurkavishmantha/Efficient-Cost-Effective-and-Time-Saving-Home-Construction-System"
              />
            </div>
          </div>

          <div className=" items-center grid w-full grid-cols-12 gap-16 border-2 border-solid p-9 rounded-lg border-dark">
            <LatestProject
              img={project4}
              title="Weather Application"
              summary="WeatherCast is a reliable and feature-rich weather application that equips users with accurate weather forecasts and real-time weather updates for multiple locations. By providing detailed information on temperature, humidity, and weather conditions, our application empowers users to make informed decisions based on weather conditions. Whether planning a trip or staying informed about local weather changes, WeatherCast ensures users are well-prepared for any weather situation."
              technology="React JS"
              link="https://github.com/chathurkavishmantha/Weather-app"
              viewPage="https://chathurka-weather-app.netlify.app/"
            />
          </div>

          <div className=" mt-10 mb-10 items-center grid w-full grid-cols-12 gap-16 ">
            <div className="col-span-6 min-h-[850px] flex flex-col border-2 border-solid p-9 rounded-lg border-dark">
              <FeaturedProjects
                img={project5}
                title="Hotel App Prototype "
                summary="Hotel Explorer is a cutting-edge hotel app that revolutionizes the way travelers search and book hotels. "
                technology="React JS,TailwindCSS"
                link="https://sl-hotel-app.netlify.app/"
                viewPage="https://github.com/chathurkavishmantha/HotelApp"
              />
            </div>
            
            {/* <div className="col-span-6 min-h-[850px] flex flex-col border-2 border-solid p-9 rounded-lg border-dark">
              <FeaturedProjects
                img={project3}
                title="Fitness Web Application"
                summary="Unrivaled Gym. Unparalleled Training Fitness Classes. World Class Studios to get the Body Shapes That you Dream of.. Get Your Dream Body Now.."
                technology="React JS, Laravel (PHP), Flask(Python), Machine Learning (ML),
                            Bootstrap and CSS"
                link="https://github.com/chathurkavishmantha/Efficient-Cost-Effective-and-Time-Saving-Home-Construction-System"
                viewPage="https://github.com/chathurkavishmantha/Efficient-Cost-Effective-and-Time-Saving-Home-Construction-System"
              />
            </div> */}
          </div>


        </Layout>
      </main>
    </>
  );
};

export default projects;
